version: "3.8"
services:
  postgres:
    image: postgres:18
    container_name: movies_db_postgres
    environment:
      POSTGRES_DB: movies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres_test:
    image: postgres:18
    container_name: movies_db_postgres_test
    environment:
      POSTGRES_DB: movies_db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql

volumes:
  postgres_data:
  postgres_test_data:
